MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '../model/pre/resnet101_ibn_b.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'resnet101_ibn_b'
  DEVICE_ID: ('0')
  ID_LOSS_TYPE: 'arcface'
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  POOLING_METHOD: 'GeM'
  WEIGHTED_TRIPLET: True
  NO_MARGIN: True
  THRESH: 0.3

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing #0.5
  PADDING: 10

DATASETS:
  NAMES: ('naic')
  ROOT_DIR: ('../data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: 'Ranger'
  MAX_EPOCHS: 50
  BASE_LR: 0.006
  IMS_PER_BATCH: 208 #128
  STEPS: [25, 40]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  COSINE_MARGIN: 0.4
  COSINE_SCALE: 30
  CENTER_LOSS_WEIGHT: 0.003
  FP16: False

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: True
  WEIGHT: '../model/a/resnet101_ibn_b_50.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'on'
OUTPUT_DIR: "../model/b/"


